# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.comb_wind <- function(pos, min_dist, max_dist) {
    .Call('LDtools_comb_wind', PACKAGE = 'LDtools', pos, min_dist, max_dist)
}

.comb_wind_sets <- function(indices_a, indices_b, pos_a, pos_b, min_dist, max_dist) {
    .Call('LDtools_comb_wind_sets', PACKAGE = 'LDtools', indices_a, indices_b, pos_a, pos_b, min_dist, max_dist)
}

.comb_adj <- function(pos) {
    .Call('LDtools_comb_adj', PACKAGE = 'LDtools', pos)
}

.comb_all <- function(pos) {
    .Call('LDtools_comb_all', PACKAGE = 'LDtools', pos)
}

.comb_all_sets <- function(indices_a, indices_b, pos_a, pos_b) {
    .Call('LDtools_comb_all_sets', PACKAGE = 'LDtools', indices_a, indices_b, pos_a, pos_b)
}

.comb_flank_sets <- function(indices_a, indices_b, pos_a, pos_b) {
    .Call('LDtools_comb_flank_sets', PACKAGE = 'LDtools', indices_a, indices_b, pos_a, pos_b)
}

.comb_nearest_k_sets <- function(indices_a, indices_b, pos_a, pos_b, k) {
    .Call('LDtools_comb_nearest_k_sets', PACKAGE = 'LDtools', indices_a, indices_b, pos_a, pos_b, k)
}

.comb_sliding <- function(pos, start, width, advance) {
    .Call('LDtools_comb_sliding', PACKAGE = 'LDtools', pos, start, width, advance)
}

.comb_sliding_set <- function(indices_a, indices_b, pos_a, pos_b, start, width, advance) {
    .Call('LDtools_comb_sliding_sets', PACKAGE = 'LDtools', indices_a, indices_b, pos_a, pos_b, start, width, advance)
}

.index_geq <- function(x, y) {
    .Call('LDtools_index_geq', PACKAGE = 'LDtools', x, y)
}

.index_greater <- function(x, y) {
    .Call('LDtools_index_greater', PACKAGE = 'LDtools', x, y)
}

.find_closest <- function(x, y) {
    .Call('LDtools_find_closest', PACKAGE = 'LDtools', x, y)
}

.center_matrix <- function(X, center) {
    invisible(.Call('LDtools_center_matrix', PACKAGE = 'LDtools', X, center))
}

#' @export
.LD <- function(x, y, px, py, any_na, is_phased, r_only) {
    .Call('LDtools_LD', PACKAGE = 'LDtools', x, y, px, py, any_na, is_phased, r_only)
}

#' @export
.LD_mult <- function(X, p, matr, is_phased, any_na) {
    .Call('LDtools_LD_mult', PACKAGE = 'LDtools', X, p, matr, is_phased, any_na)
}

#' @export
.LD_mult_r_dev <- function(X, p, matr, is_phased, any_na, cache) {
    .Call('LDtools_LD_mult_r_dev', PACKAGE = 'LDtools', X, p, matr, is_phased, any_na, cache)
}

#' @export
.LD_mult_r <- function(X, p, matr, is_phased, any_na) {
    .Call('LDtools_LD_mult_r', PACKAGE = 'LDtools', X, p, matr, is_phased, any_na)
}

get_counts <- function(x, y) {
    .Call('LDtools_get_counts', PACKAGE = 'LDtools', x, y)
}

#' @export
.optimum_pxy <- function(n3x3, px, py, lower, upper) {
    .Call('LDtools_optimum_pxy', PACKAGE = 'LDtools', n3x3, px, py, lower, upper)
}

.sliding_window <- function(x, pos, start, width, advance, stat) {
    .Call('LDtools_sliding_window', PACKAGE = 'LDtools', x, pos, start, width, advance, stat)
}

